### PR TITLE
Add serverOnly prop to skip client side render

### PR DESCRIPTION
**Pull request by jaylynch**
We're SSR-only for `<head>` stuff at the moment and need `<meta>` tags and the like to not be cluttered - it is a validation issue for AMP. Even if it weren't I don't like having them when they're not needed.

This adds a `serverOnly` prop which will skip the client render entirely and strip out the `data-rh=""` properties.

I've not tested with the suggested dev server because of https://github.com/tizmagik/react-head/issues/64 but am using it in a fairly substantial project and have provided tests.

### CODE REVIEW

**Comment by TrySound** [comment]
It feels wrong that AMP forbids generic `data-*` attributes. They were introduced especially to be affect semantic anyhow.

The new serverOnly option breaks (skips) rendering on client which is also not good because it leads to inconsistency between client and server we are trying to omit.

If you need to make it work in AMP just remove `data-rh` attributes from `headTags` before sending to server. It's simple string replace operation. For client side you may remove these specific tags in `componentDidMount`.

**Comment by tizmagik** [comment]
I can appreciate this use case -- I have to deal with AMP too 😅 

But I think I'm with @TrySound on this, it feels wrong to short-circuit the client-render, especially when in AMP the code won't even run.

Would doing a string-replace on `data-rh` attribute work for you @jaylynch ?

**Comment by jaylynch** [comment]
Breaking the client render was intentional, precisely because it won't run. It also prevents it needlessly generating / appending tags when the JS does run, eg. our main site, where we are doing SSR-only at the moment with regular `<a href="">` tags for links.

I don't use one but would imagine most static site generators would be able to make use of something similar.

String replaces are fine but I find having a config option on the meta tag generator far less uncomfortable than running regexes on HTML strings that are going to be sent to a browser.

If nothing else we allow (internal) users to embed tags, scripts, etc. in body content that we can't know about in advance, running string replaces to try to alter data attributes feels dangerous.

**Comment by TrySound** [comment]
My point is that tags should be "rehydrated" in client side in any case to prevent any inconsistencies. Otherwise we will step away from react philosophy and break something eventually. If something works to workaround this I would stick with it.

**Comment by tizmagik** [comment]
Would be happy to explore some more ways to support the AMP use case better, but looks like this PR has gone stale. Please feel free to re-open or submit a follow-on PR with any more ideas. Thank you! 🙏

**Pull request closed without merging**
